version: "3"
services:
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
      environment:
          discovery.type: single-node
      volumes:
          - elastic-data:/usr/share/elasticsearch/data
      ports:
          - 9200:9200
      networks:
          - backend

  kibana:
      image: docker.elastic.co/kibana/kibana-oss:6.2.3
      depends_on:
          - elasticsearch
      ports:
          - 5601:5601
      networks:
          - backend

networks:
    backend:

volumes:
    elastic-data: