version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    ports:
      - 5601:5601
    networks:
      - backend
    depends_on:
      - elasticsearch
    environment:
      xpack.security.enabled: "false"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    ports:
      - 9200:9200
    networks:
      - backend
    environment:
      discovery.type : single-node
    #   SERVER_NAME: kibana.example.org
    #   ELASTICSEARCH_URL: http://localhost.example.org

networks:
  backend: